### ISSUE TITLE
No static getter 'file' declared in class 'FileSystemEntityType'.

### ISSUE THREAD

**Issue by joshunger** [timsneath/github-tracker#1]
```
➜  github-tracker git:(master) dart repo-stars.dart
Unhandled exception:
NoSuchMethodError: No static getter 'file' declared in class 'FileSystemEntityType'.
Receiver: Type: class 'FileSystemEntityType'
Tried calling: file
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:196)
#1      cacheMissingOrInvalidated (file:///Users/junger/dropbox/dev/github-tracker/repo-stars.dart:103:68)
#2      main (file:///Users/junger/dropbox/dev/github-tracker/repo-stars.dart:92:32)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Does this need to be `FileSystemEntityType.FILE` ?

**Comment by timsneath** [comment]
I think you may have an older version of Dart? What does `dart --version` show? 

By way of explanation, in the run-up to Dart 2, the team introduced [lowerCamelCase as the preferred style](https://www.dartlang.org/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names) for constants and deprecated upper-case constants. I'm running at the tip, so I switched to the latest style.

Can you try this from a later version of Dart and see if you're still having problems?

**Comment by joshunger** [comment]
Looks like `brew install dart` installs `Dart VM version: 1.24.3 (Wed Dec 13 23:26:59 2017) on "macos_x64"`.  

Looks like `brew install dart --devel` installs `Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "macos_x64"`

**Comment by timsneath** [comment]
Oh, yes. 1.24 is pretty old now. We are really close to marking 2.0 as stable now, and in fact I'd recommend it over 1.24 at this point. Would you mind installing the devel version instead and seeing if that works for you?

**Comment by timsneath** [comment]
Ah, looks like you pulled down some pre-Dart 2 package dependencies while you had the old version installed. Run `pub upgrade` to get the latest, and then you should finally be there!

**Comment by joshunger** [comment]
We did it ✋thanks!
